"""add medical dashboard schema

Revision ID: 0012fb49dc84
Revises: 507d7bb35761
Create Date: 2026-09-02 23:30:22.513462
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0012fb49dc84'
down_revision: Union[str, Sequence[str], None] = '507d7bb35761'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ward',
    sa.Column('ward_code', sa.String(length=32), nullable=False),
    sa.Column('ward_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('ward_code', name=op.f('pk_ward'))
    )
    op.create_table('patient_profile',
    sa.Column('patient_id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('patient_code', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=50), nullable=False),
    sa.Column('ward_code', sa.String(length=32), nullable=False),
    sa.Column('room_number', sa.String(length=32), nullable=False),
    sa.Column('admitted_on', sa.Date(), nullable=False),
    sa.Column('communication_status', sa.String(length=32), nullable=False),
    sa.Column('assistive_method', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_patient_profile_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ward_code'], ['ward.ward_code'], name=op.f('fk_patient_profile_ward_code_ward'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('patient_id', name=op.f('pk_patient_profile')),
    sa.UniqueConstraint('patient_code', name=op.f('uq_patient_profile_patient_code')),
    sa.UniqueConstraint('user_id', name=op.f('uq_patient_profile_user_id'))
    )
    op.create_index('ix_patient_profile_admitted_on', 'patient_profile', ['admitted_on'], unique=False)
    op.create_index('ix_patient_profile_ward_room', 'patient_profile', ['ward_code', 'room_number'], unique=False)
    op.create_table('staff_ward_access',
    sa.Column('staff_user_id', sa.Integer(), nullable=False),
    sa.Column('ward_code', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['staff_user_id'], ['users.user_id'], name=op.f('fk_staff_ward_access_staff_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ward_code'], ['ward.ward_code'], name=op.f('fk_staff_ward_access_ward_code_ward'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('staff_user_id', 'ward_code', name=op.f('pk_staff_ward_access'))
    )
    op.create_table('communication_request',
    sa.Column('request_id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('utterance_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('ward_code', sa.String(length=32), nullable=False),
    sa.Column('room_number', sa.String(length=32), nullable=False),
    sa.Column('phrase_code', sa.String(length=64), nullable=True),
    sa.Column('text', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('priority', sa.String(length=16), server_default=sa.text("'NORMAL'"), nullable=False),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'NEW'"), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_by', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_by', sa.Integer(), nullable=True),
    sa.Column('resolution_note', sa.String(length=500), nullable=True),
    sa.CheckConstraint("priority IN ('NORMAL', 'HIGH', 'CRITICAL')", name=op.f('ck_communication_request_priority')),
    sa.CheckConstraint("status IN ('NEW', 'ACKNOWLEDGED', 'COMPLETED')", name=op.f('ck_communication_request_status')),
    sa.CheckConstraint('confidence IS NULL OR (confidence >= 0 AND confidence <= 1)', name=op.f('ck_communication_request_confidence_range')),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.user_id'], name=op.f('fk_communication_request_acknowledged_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['completed_by'], ['users.user_id'], name=op.f('fk_communication_request_completed_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profile.patient_id'], name=op.f('fk_communication_request_patient_id_patient_profile'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['utterance_id'], ['utterance.utt_id'], name=op.f('fk_communication_request_utterance_id_utterance'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('request_id', name=op.f('pk_communication_request')),
    sa.UniqueConstraint('utterance_id', name=op.f('uq_communication_request_utterance_id'))
    )
    op.create_index('ix_communication_request_patient_requested_at', 'communication_request', ['patient_id', 'requested_at'], unique=False)
    op.create_index('ix_communication_request_status_priority_requested_at', 'communication_request', ['status', 'priority', 'requested_at'], unique=False)
    op.create_index('ix_communication_request_ward_requested_at', 'communication_request', ['ward_code', 'requested_at'], unique=False)
    op.create_table('request_event',
    sa.Column('event_id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=16), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.CheckConstraint("event_type IN ('REQUESTED', 'ACKNOWLEDGED', 'COMPLETED')", name=op.f('ck_request_event_event_type')),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.user_id'], name=op.f('fk_request_event_actor_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['request_id'], ['communication_request.request_id'], name=op.f('fk_request_event_request_id_communication_request'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', name=op.f('pk_request_event'))
    )
    op.create_index('ix_request_event_request_occurred_at', 'request_event', ['request_id', 'occurred_at'], unique=False)
    op.create_table('request_idempotency',
    sa.Column('idempotency_id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('operation', sa.String(length=16), nullable=False),
    sa.Column('request_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("operation IN ('ACKNOWLEDGE', 'COMPLETE')", name=op.f('ck_request_idempotency_operation')),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.user_id'], name=op.f('fk_request_idempotency_actor_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['request_id'], ['communication_request.request_id'], name=op.f('fk_request_idempotency_request_id_communication_request'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('idempotency_id', name=op.f('pk_request_idempotency')),
    sa.UniqueConstraint('actor_user_id', 'idempotency_key', name=op.f('uq_request_idempotency_actor_user_id'))
    )
    op.create_index('ix_request_idempotency_request_id', 'request_idempotency', ['request_id'], unique=False)
    op.add_column('users', sa.Column('role', sa.String(length=16), server_default='PATIENT', nullable=False))
    op.create_check_constraint(
        op.f('ck_users_role'),
        'users',
        "role IN ('PATIENT', 'STAFF')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f('ck_users_role'),
        'users',
        type_='check',
    )
    op.drop_column('users', 'role')
    op.drop_index('ix_request_idempotency_request_id', table_name='request_idempotency')
    op.drop_table('request_idempotency')
    op.drop_index('ix_request_event_request_occurred_at', table_name='request_event')
    op.drop_table('request_event')
    op.drop_index('ix_communication_request_ward_requested_at', table_name='communication_request')
    op.drop_index('ix_communication_request_status_priority_requested_at', table_name='communication_request')
    op.drop_index('ix_communication_request_patient_requested_at', table_name='communication_request')
    op.drop_table('communication_request')
    op.drop_table('staff_ward_access')
    op.drop_index('ix_patient_profile_ward_room', table_name='patient_profile')
    op.drop_index('ix_patient_profile_admitted_on', table_name='patient_profile')
    op.drop_table('patient_profile')
    op.drop_table('ward')
    # ### end Alembic commands ###
