"""create auth tables

Revision ID: b8066cc1edc8
Revises: 20260720_0001
Create Date: 2026-08-13 13:49:50.467530
"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

revision: str = 'b8066cc1edc8'
down_revision: Union[str, Sequence[str], None] = '20260720_0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('hospital', sa.String(length=100), nullable=False),
    sa.Column('ward', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('login_session',
    sa.Column('login_session_id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_token', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_login_session_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('login_session_id', name=op.f('pk_login_session')),
    sa.UniqueConstraint('session_token', name=op.f('uq_login_session_session_token'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('login_session')
    op.drop_table('users')
    # ### end Alembic commands ###
